version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/workspace
    steps:
      - checkout

      - run:
          name: Install latest bundlewatch
          command: yarn add bundlewatch

      - run:
          name: Run bundlewatch check
          command: DEBUG=true yarn bundlewatch --config config.bundlewatch.js
